version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
      - run: 
          name: Install apt dependencies
          command: sudo apt-get update && sudo apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn test:ci
      - run: 
          name: Deploy on master
          command: '[ $CIRCLE_BRANCH == "master" ] && yarn deploy:ci || echo "Not on master"'